### ISSUE TITLE
Works on 8ch, not 4chan

### ISSUE THREAD

**Issue by compile10** [calumks/safari-embedded-webm-support#1]
Thanks for writing this plugin. 

On safari 10.1 it works on 8ch but on 4chan it does not. The webm opens in a new window like normal and the superscript disappears from the active scripts list until the page is refreshed.

**Comment by teaqu** [comment]
Ah! I forgot to test this without [4chan X](https://github.com/ccd0/4chan-x).

**Comment by compile10** [comment]
Would you mind posting your 4chan x config? When I try it with 4chan x, it works simply throws the video at the top instead of the page below the blotter instead of the normal positioning.

**Comment by teaqu** [comment]
Never noticed how badly 4chan runs on Safari without 4chan X. I'm going to just going to make 4chan X a requirement for this script as it fixes a lot of bugs. 

I reset my config and got the same issue as you. Disable Image Hover in the settings and that should fix it.

**Comment by compile10** [comment]
Alright, thanks for the help!

**Comment by teaqu** [comment]
Did that fix it for you? Thanks for reporting!

**Comment by compile10** [comment]
Yep. No problems. Great userscript BTW, I thought I would have to write something like this myself. Thanks.
