### ISSUE TITLE
4chan embedding still not working for me

### ISSUE THREAD

**Issue by Mazuo** [calumks/safari-embedded-webm-support#2]
Having the same problem described in the first (now closed) issue.
Script works on 8chan but when I click a WebM on 4chan, nothing happens.
However, installing 4chanX and disabling "hover" did not fix it for me as it did for the other user.

I repeated the installation of Tampermonkey, VLC webplugin, 4chanX (disabled Hover), and this script many times.

Along the way I tried different things:
-Clearing all browser data (standard method and with 3rd party programs)
-Reinstalling all the extensions, plugins, and scripts in different orders.
-Checking permissions (preferences>security>plugin settings)
-restarting browser and computer (mac osx Sierra)
-tried different versions of VLCwebplugin (older, current, and experimental)

But after all that still no success.
I am out of ideas at this point and could use some assistance.

Thanks

**Comment by Mazuo** [comment]
Pinned down the problem!

The WebMs will not embed when using the "HTTPS" version of 4chan.org
The script works as intended when browsing on the "HTTP" version of the site.

So it is the secure version of 4chan that messes up the script for me.

Is there a setting I can change that will fix this?

**Comment by teaqu** [comment]
Thanks for reporting and narrowing down the problem! I've updated the script and it should now match both http and https.
