### ISSUE TITLE
Unsupported Plug-in + Support for 4channel

### ISSUE THREAD

**Issue by SlippyKorny** [calumks/safari-embedded-webm-support#6]
Script won't load on 4channel boards out of the box (I needed to add a "// @match        *://boards.4channel.org/*" line). I'm always getting an error that says "Unsupported plug-in" each time I try to watch a webm video on both 4chan and 8chan. My safari version is 12.0.3.

**Comment by SlippyKorny** [comment]
Just did a quick google search and according to a thread on videolan forum (https://forum.videolan.org/viewtopic.php?t=146878) safari ended plugin support some time ago. So I suppose if anybody wants to watch webms one should download Firefox or Chrome.

**Comment by teaqu** [comment]
Damn that sucks T_T.
